### ISSUE TITLE
List of redudant labs running on IIIT-H and AWS 

### ISSUE THREAD

**Issue by ksripathi** [openedx-vlead/vlabs-analytics-api-server#3]
There are few labs which are running from both the environments AWS cloud and IIIT-H.
This issue captures  list of such url

**Comment by ksripathi** [comment]
@sivashankerN 

Please find the list of all labs running on base3(IIIT-H) at https://bitbucket.org/vlead/vlead/src/ecde30a456eb9e4a758008b6b1a28baafa3b27b1/projects/cleaning-deploy/labs-on-base2.org?at=master&fileviewer=file-view-default

And please stop the containers on base3 which are not required

**Comment by ksripathi** [comment]
@sivashankerN 

Any update on this ??

**Comment by sivashankerN** [comment]
@ksripathi it is done long back.

Still if you find any redundant lab running, please let us know. please check this link if you have permissions to this project/repo

**Comment by sivashankerN** [comment]
https://gitlab.com/vlead-systems/docs/blob/master/src/base-machines-docs/base3/stop-labs-on-base3-iiith.org

**Comment by ksripathi** [comment]
@sivashankerN 
Thanks
